### ISSUE TITLE
Can not install latest tinygo on MaOS 

### ISSUE THREAD

**Issue by timanovsky** [troyjfarrell/asdf-tinygo#3]
Hi, thanks for doing this project. Wanted to report couple of issues
**Describe the bug**

1. Installation of latest (0.34.0 as of now) is silently failing

```
asdf install tinygo 0.34.0
* Downloading tinygo release 0.34.0...
```

2. Installing 0.33.0 goes fine however prints error while installation

```
% asdf install tinygo 0.33.0                                                              
* Downloading tinygo release 0.33.0...
/Users/timanovsky/.asdf/plugins/tinygo/lib/utils.bash: line 79: [: : integer expression expected
tinygo0.33.0.darwin-arm64.tar.gz: OK
tinygo 0.33.0 installation was successful!
```
 

**Steps to reproduce**

OS version:

```
% uname -a
Darwin at-MacBook 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:36 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6020 arm64
````

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by troyjfarrell** [comment]
I have added SHA-256 values for TinyGo 0.34.0 in b5309d2d00.  I really wish that they would sign releases so I don't have to manage hashes manually.

```bash
$HOME/.asdf.plugins/tinygo/lib/utils.bash: line 79: [: : integer expression expected
```

This appears to happen because `wc` on macOS has some space to the left of the number, while GNU `wc` does not.  I've added `awk '{print $1}'` to fix that.  (I don't work on macOS regularly thus I had not tested the scripts there before today.)

This is fixed in a78a68ac57.
